"$schema": "https://schemas.meshmakers.cloud/construction-kit-elements.schema.json"
types:
- typeId: Entity
  isFinal: false
  isAbstract: true
- typeId: AutoIncrement
  derivedFromCkTypeId: System/Entity
  isFinal: false
  isAbstract: false
  attributes:
    - id: System/AutoIncrement.Start
      name: Start
    - id: System/AutoIncrement.End
      name: End
    - id: System/AutoIncrement.CurrentValue
      name: CurrentValue
- typeId: Tenant
  derivedFromCkTypeId: System/Entity
  isFinal: true
  isAbstract: false
  attributes:
  - id: System/TenantId
    name: TenantId
  - id: System/DatabaseName
    name: DatabaseName
  indexes:
  - indexType: Ascending
    fields:
    - attributeNames:
      - TenantId
- typeId: Configuration
  derivedFromCkTypeId: System/Entity
  isFinal: true
  isAbstract: false
  attributes:
    - id: System/ConfigurationValue
      name: ConfigurationValue
