"$schema": "https://schemas.meshmakers.cloud/construction-kit-elements.schema.json"
types:
- typeId: Configuration
  derivedFromCkTypeId: System/Entity
  isFinal: true
  isAbstract: false
  attributes:
    - id: System/ConfigurationValue
      name: ConfigurationValue
      isOptional: true
